<?php
   if ($exist = ($this->getFeaturedProduct() && $this->getFeaturedProduct()->getSize())) 
   {
      $fet_prodcollection = $this->getFeaturedProduct();
      $productcount = $this->getData('productcount');
      $imagewidth = $this->getData('imagewidth') ? $this->getData('imagewidth') : 270;
      $imageheight = $this->getData('imageheight') ? $this->getData('imageheight') : 224;
      $mode = 'grid';
      $title = __('Features');
      $type = 'widget-featured-grid';
      $image = 'featured_products_content_widget_grid';
   }
   ?>
<?php if ($exist): ?>
<div class="block widget block-featured-products <?php echo $mode; ?>">
   <div class="block-title">
      <h2 class="title"> <?php echo $title ?></h2>
      <p class="info"> <?php echo __("Here's whats trending on B&O right now"); ?></p>
   </div>
   <div class="block-content">
      <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
         <ol class="product-items <?php echo $type; ?>">
            <?php $iterator = 1; ?>
            <?php foreach($fet_prodcollection as $_product): ?>
            <?php echo ($iterator++ == 1) ? 
               '<li class="product-item">':
               '</li><li class="product-item">';
               ?>
            <div class="product-item-info">
               <?php 
                    $image_url = $block->imageHelperObj()
                        ->init($_product, 'product_page_image_small')
                        ->setImageFile($_product->getFile())
                        ->resize($imagewidth, $imageheight)
                        ->getUrl();
                  ?>
               <a href="<?php echo $_product->getProductUrl() ?>" class="product-item-photo">
               <img src="<?php
                  echo $image_url; ?>" alt="<?php
                  echo $this->escapeHtml($_product->getName()) ?>" />
               </a>
               <div class="product-item-details">
                  <div class="product-item-name">
                     <a title="<?php
                        echo $block->escapeHtml($_product->getName()) ?>"
                        href="<?php echo $_product->getProductUrl() ?>"
                        class="product-item-link">
                     <?php echo $block->escapeHtml($_product->getName()) ?>
                     </a>
                  </div>
                  <div class="product-item-desc">
                     <?php echo $_product->getDescription(); ?>
                  </div>
                  <div class="product-item-price">
                     <?php echo $this->getProductPriceHtml($_product, $type);?>
                  </div>
                  <div class="product-item-actions">
                     <div class="actions-primary">
                        <?php
                           if ($_product->isSaleable()): ?>
                        <?php
                           if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                        <button class="action tocart primary"
                           data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                              echo $block->getAddToCartUrl($_product) ?>"}}'
                           type="button" title="<?php echo __('Add to Cart') ?>">
                        <span><?php echo __('Add to Cart') ?></span>
                        </button>
                        <?php
                           else: ?>
                        <?php
                           $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                           $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product) , ['product' => $_product->getId() ]);
                           ?>
                        <button class="action tocart primary"
                           data-post='<?php echo $postData; ?>'
                           type="button" title="<?php echo __('Add to Cart') ?>">
                        <span><?php echo __('Add to Cart') ?></span>
                        </button>
                        <?php
                           endif; ?>
                        <?php
                           else: ?>
                        <?php
                           if ($_product->getIsSalable()): ?>
                        <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                        <?php
                           else: ?>
                        <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                        <?php
                           endif; ?>
                        <?php
                           endif; ?>
                     </div>
                  </div>
               </div>
            </div>
            <?php echo ($iterator == count($fet_prodcollection) + 1) ? '</li>' : '' ?>
            <?php endforeach ?>
         </ol>
      </div>
   </div>
</div>
<?php endif; ?>